# Generated by Django 5.2.8 on 2025-12-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mentor",
            old_name="f_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="f_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="l_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="l_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll_no",
        ),
        migrations.AddField(
            model_name="student",
            name="mid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.mentor",
            ),
        ),
    ]
