# Generated by Django 5.2.8 on 2025-12-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_f_name_mentor_name_rename_f_name_student_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentor",
            name="end_roll_no",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="start_roll_no",
        ),
    ]
