# Generated by Django 5.2.8 on 2025-12-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_mentor_end_roll_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mid",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.mentor",
            ),
        ),
    ]
