# Generated by Django 5.2.8 on 2025-12-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_student_mid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentor",
            name="sem",
        ),
        migrations.AlterField(
            model_name="mentor",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
