# Generated by Django 5.2.8 on 2025-12-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_mentor_sem_alter_mentor_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
    ]
