# Generated by Django 5.2.8 on 2025-12-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
    ]
