# Generated by Django 5.2.8 on 2025-12-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_mentor_name_remove_student_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="max_sessions",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[("accept", "Accepted"), ("request", "Requested")],
                max_length=20,
            ),
        ),
    ]
