# Generated by Django 5.2.8 on 2025-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_student_max_sessions_alter_session_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="anon",
            field=models.BooleanField(default=False),
        ),
    ]
