# Generated by Django 5.2.8 on 2025-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_session_anon"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
