# Generated by Django 5.2.8 on 2025-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_session_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
