# Generated by Django 5.2.8 on 2025-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_session_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("accept", "Accepted"),
                    ("request", "Requested"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
