# Generated by Django 5.2.8 on 2025-12-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_session_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="mid",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="sid",
        ),
        migrations.AddField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.session",
            ),
            preserve_default=False,
        ),
    ]
