# Generated by Django 5.2.8 on 2025-12-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_feedback_mid_remove_feedback_sid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="api.session",
            ),
        ),
    ]
