# Generated by Django 5.2.8 on 2025-12-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_feedback_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="session",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="feedback",
            name="anon",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="mid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.mentor",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="sid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.student",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
