# Generated by Django 5.2.8 on 2025-12-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_feedback_session_remove_feedback_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
